version: '3'

services:
  message-broker:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - '61613:61613' # STOMP port
      - '8161:8161' # admin port
    environment:
      ANONYMOUS_LOGIN: 'true'
    restart: always
  command-server:
    build: ./command-server
    ports:
      - '8000:8000'
    depends_on:
      - message-broker
